/** 
 * ============================================================================
 * Xirp 2: eXtendable interface for robotic purposes.
 * ============================================================================
 * 
 * Copyright (C) 2005-2007, by Authors and Contributors listed in CREDITS.txt
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Common Public License v1.0
 * which accompanies this distribution, and is available at:
 *
 * 				http://www.opensource.org/licenses/cpl1.0.php
 *
 * ----------------------------
 * Command.java
 * ----------------------------
 *
 * Original Author:  Rabea Gransberger [rgransberger AT web.de]
 * Contributor(s):   
 *
 * Changes
 * -------
 * 10.02.2007:		Created by Rabea Gransberger.
 */
package de.xirp.io.command;

import java.util.List;

/**
 * A command.
 * 
 * @author Rabea Gransberger
 */
public class Command {

	/**
	 * The type of the generator which generated a command
	 * 
	 * @author Rabea Gransberger
	 */
	public enum GeneratorType {
		/**
		 * Command was generated by a plugin
		 */
		PLUGIN,
		/**
		 * Command was generated by a keyboard
		 */
		CHAR_INPUT_DEVICE,
		/**
		 * Command was generated by a joystick or gamepad
		 */
		JOYSTICK,
		/**
		 * Command was generated from a speech to text engine
		 */
		SPEECH,
		/**
		 * Any other command generator
		 */
		MISC;
	}

	/**
	 * The definition of the command
	 */
	private CommandDefinition def;
	/**
	 * The parameter values for the command definition
	 */
	private List<String> parameterValues;
	/**
	 * The timestamp at which the command was triggered
	 */
	private long timestamp;
	/**
	 * The object which generated the command
	 */
	private Object generator;
	/**
	 * The type of the generator
	 */
	private GeneratorType type;

	/**
	 * Constructs a new command.
	 * 
	 * @param generator
	 *            the instance which created the command
	 * @param timestamp
	 *            the time when the command was created
	 * @param type
	 *            the type of the generator
	 * @param def
	 *            the original command definition
	 * @param parameterValues
	 *            the values for the command parameters
	 */
	public Command(Object generator, long timestamp, GeneratorType type,
			CommandDefinition def, List<String> parameterValues) {
		this.generator = generator;
		this.timestamp = timestamp;
		this.type = type;
		this.def = def;
		this.parameterValues = parameterValues;
	}

	/**
	 * The type of the generator.
	 * 
	 * @return the type
	 */
	public GeneratorType getType() {
		return type;
	}

	/**
	 * The object which generated the command.
	 * 
	 * @return the generator
	 */
	public Object getGenerator() {
		return generator;
	}

	/**
	 * The definition of the command.
	 * 
	 * @return the name
	 */
	public CommandDefinition getCommandDefinition() {
		return def;
	}

	/**
	 * The parameter values for the command definition.
	 * 
	 * @return the parameterValues
	 */
	public List<String> getParameterValues() {
		return parameterValues;
	}

	/**
	 * The timestamp at which the command was triggered.
	 * 
	 * @return the timestamp
	 */
	public long getTimestamp() {
		return timestamp;
	}

}
